[build]
  publish = "public"
  command = "npm run build:lambda && gatsby build"
  functions = "./lambda"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/functions/twilio"
    [headers.values]
    Access-Control-Allow-Origin = "*"